/**
 * GENERATED FROM THE ONTOLOGY AND THE PUBLIC REGISTRY — do not edit by hand.
 *
 * Source: `~/skills/ontology/northern-colorado.ttl` (an A-box over `fieldops.tbox.ttl`, under faith and story), joined on each
 * community's registry IRI with `registry.generated.ts` (gc-public, read 2026-10-01T20:55:25.044Z).
 * Rebuild: `pnpm gen:fieldops`
 */
import type { Region, Scenario } from '../types.js';

export const NORTHERN_COLORADO_FROM_ONTOLOGY: Region = {
  id: "northern-colorado",
  name: "Northern Colorado",
  blurb: "The Front Range north of Denver and the plains east of it: four corridors, nineteen towns, and the people communities the public registry says are there.",
  registryReadAt: "2026-10-01T20:55:25.044Z",
  corridors: [
    { id: "weld", name: "Greeley / Weld County corridor", counties: ["Weld"], towns: ["greeley", "evans", "windsor", "fort-lupton", "johnstown", "eaton"] },
    { id: "larimer", name: "Northern Front Range / Larimer", counties: ["Larimer"], towns: ["fort-collins", "loveland", "wellington", "berthoud"] },
    { id: "boulder", name: "Boulder / Broomfield / Longmont corridor", counties: ["Boulder", "Broomfield"], towns: ["boulder", "longmont", "lafayette", "broomfield"] },
    { id: "plains", name: "Northeast Plains", counties: ["Morgan", "Logan", "Yuma"], towns: ["fort-morgan", "sterling", "brush", "yuma"] },
  ],
  towns: [
    { id: "greeley", name: "Greeley", corridor: "weld", lat: 40.4233, lng: -104.7091, population: 135270, churches: 68 },
    { id: "evans", name: "Evans", corridor: "weld", lat: 40.3764, lng: -104.6922, population: 21727, churches: 9 },
    { id: "windsor", name: "Windsor", corridor: "weld", lat: 40.4775, lng: -104.9014, population: 31972, churches: 36 },
    { id: "fort-lupton", name: "Fort Lupton", corridor: "weld", lat: 40.0847, lng: -104.813, population: 7947, churches: 14 },
    { id: "johnstown", name: "Johnstown", corridor: "weld", lat: 40.3369, lng: -104.9122, population: 16596, churches: 13 },
    { id: "eaton", name: "Eaton", corridor: "weld", lat: 40.5303, lng: -104.7113, population: 5648, churches: 18 },
    { id: "fort-collins", name: "Fort Collins", corridor: "larimer", lat: 40.5853, lng: -105.0844, population: 169800, churches: 160 },
    { id: "loveland", name: "Loveland", corridor: "larimer", lat: 40.3978, lng: -105.075, population: 76400, churches: 120 },
    { id: "wellington", name: "Wellington", corridor: "larimer", lat: 40.7039, lng: -105.0086, population: 11000, churches: 15 },
    { id: "berthoud", name: "Berthoud", corridor: "larimer", lat: 40.3083, lng: -105.0811, population: 10300, churches: 14 },
    { id: "boulder", name: "Boulder", corridor: "boulder", lat: 40.015, lng: -105.2705, population: 105000, churches: 150 },
    { id: "longmont", name: "Longmont", corridor: "boulder", lat: 40.1672, lng: -105.1019, population: 98000, churches: 130 },
    { id: "lafayette", name: "Lafayette", corridor: "boulder", lat: 39.9936, lng: -105.0897, population: 30400, churches: 35 },
    { id: "broomfield", name: "Broomfield", corridor: "boulder", lat: 39.9205, lng: -105.0867, population: 74000, churches: 60 },
    { id: "fort-morgan", name: "Fort Morgan", corridor: "plains", lat: 40.2503, lng: -103.7999, population: 11600, churches: 35 },
    { id: "sterling", name: "Sterling", corridor: "plains", lat: 40.6255, lng: -103.2077, population: 13700, churches: 40 },
    { id: "brush", name: "Brush", corridor: "plains", lat: 40.2589, lng: -103.6238, population: 5500, churches: 14 },
    { id: "yuma", name: "Yuma", corridor: "plains", lat: 40.1222, lng: -102.7252, population: 3400, churches: 12 },
  ],
  communities: [
    {
      id: "burmese-weld", iri: "https://graph.global.church/community/101776rop3imb-weld", name: "Burmese — Weld", corridor: "weld",
      people: { name: "Burmese", iri: "https://graph.global.church/pg/alliance/burmese-greeley-evans-corridor", scheme: "https://graph.global.church/scheme/colorado-impact-project", ropId: "101776", peid: "47239", pgId: "PG047239", language: "burmese", homeCountry: "Myanmar" },
      towns: ["greeley", "evans"],
      population: 280,
      registry: { phase: 1, qualifier: null, resultDate: null, framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P1 (undated)","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"colorado-impact-project","source":"gc-public"},{"label":"ROP3","value":"101776","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG047239","source":"PeopleGroups.org"},{"label":"estimate basis","value":"ACS 2023 Burmese spoken at home, Weld County","source":"the season"}],
      base: { readiness: 0.55 },
    },
    {
      id: "somali-bantus-weld", iri: "https://graph.global.church/community/103458rop3imb-weld", name: "Somali Bantus — Weld", corridor: "weld",
      people: { name: "Somali Bantus", iri: "https://graph.global.church/pg/alliance/somali-bantus-greeley-evans-corridor", scheme: "https://graph.global.church/scheme/colorado-impact-project", ropId: "103458", peid: "50352", pgId: "PG050352", language: "maay", homeCountry: "Somalia" },
      towns: ["greeley", "fort-lupton"],
      population: 210,
      registry: { phase: 1, qualifier: null, resultDate: null, framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P1 (undated)","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"colorado-impact-project","source":"gc-public"},{"label":"ROP3","value":"103458","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG050352","source":"PeopleGroups.org"},{"label":"estimate basis","value":"ACS 2023 Swahili spoken at home, Weld County — a proxy, and a known mis-proxy for Maay speakers","source":"the season"}],
      base: { readiness: 0.6 },
    },
    {
      id: "guatemalans-weld", iri: "https://graph.global.church/community/103510rop3imb-weld", name: "Guatemalans — Weld", corridor: "weld",
      people: { name: "Guatemalans", iri: "https://graph.global.church/pg/alliance/guatemalans-greeley-evans-corridor", scheme: "https://graph.global.church/scheme/colorado-impact-project", ropId: "103510", peid: "46516", pgId: "PG046516", language: "spanish", homeCountry: "Guatemala" },
      towns: ["greeley", "evans", "johnstown"],
      population: 4000,
      registry: { phase: 3, qualifier: null, resultDate: "2026-06", framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P3 @ 2026-06","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"colorado-impact-project","source":"gc-public"},{"label":"ROP3","value":"103510","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG046516","source":"PeopleGroups.org"},{"label":"estimate basis","value":"author's rounded share of the county's Spanish-at-home count","source":"the season"}],
      base: { readiness: 0.45 },
    },
    {
      id: "sgaw-karen-weld", iri: "https://graph.global.church/community/100207rop3-weld", name: "S'gaw Karen — Weld", corridor: "weld",
      people: { name: "S'gaw Karen", iri: "https://graph.global.church/pg/karen", scheme: "https://graph.global.church/scheme/joshua-project", ropId: "108886", peid: "47263", pgId: "PG047263", homeCountry: "Myanmar" },
      towns: ["greeley", "evans", "windsor"],
      population: 400,
      registry: { phase: 4, qualifier: null, resultDate: "2026-08", framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P4 @ 2026-08","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"joshua-project","source":"gc-public"},{"label":"ROP3","value":"108886","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG047263","source":"PeopleGroups.org"},{"label":"estimate basis","value":"author's estimate from the resettlement record; no census line","source":"the season"}],
      base: { readiness: 0.65 },
    },
    {
      id: "afghans-larimer", iri: "https://graph.global.church/community/115238rop3imb-larimer", name: "Afghans — Larimer", corridor: "larimer",
      people: { name: "Afghans", iri: "https://graph.global.church/pg/alliance/afghans-fort-collins-loveland", scheme: "https://graph.global.church/scheme/colorado-impact-project", ropId: "115238", peid: "46478", pgId: "PG046478", language: "dari", homeCountry: "Afghanistan" },
      towns: ["fort-collins", "loveland"],
      population: 720,
      registry: { phase: 1, qualifier: null, resultDate: null, framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P1 (undated)","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"colorado-impact-project","source":"gc-public"},{"label":"ROP3","value":"115238","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG046478","source":"PeopleGroups.org"},{"label":"estimate basis","value":"ACS 2023 Persian spoken at home, Larimer County — a proxy","source":"the season"}],
      base: { readiness: 0.4 },
    },
    {
      id: "nepalis-larimer", iri: "https://graph.global.church/community/107204rop3imb-larimer", name: "Nepalis — Larimer", corridor: "larimer",
      people: { name: "Nepalis", iri: "https://graph.global.church/pg/alliance/nepalis-fort-collins-loveland", scheme: "https://graph.global.church/scheme/colorado-impact-project", ropId: "107204", peid: "43559", pgId: "PG043559", language: "nepali", homeCountry: "Nepal" },
      towns: ["fort-collins"],
      population: 380,
      registry: { phase: 1, qualifier: null, resultDate: null, framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P1 (undated)","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"colorado-impact-project","source":"gc-public"},{"label":"ROP3","value":"107204","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG043559","source":"PeopleGroups.org"},{"label":"estimate basis","value":"ACS 2023 Nepali spoken at home, Larimer County","source":"the season"}],
      base: { readiness: 0.5 },
    },
    {
      id: "vietnamese-larimer", iri: "https://graph.global.church/community/105018rop3imb-larimer", name: "Vietnamese — Larimer", corridor: "larimer",
      people: { name: "Vietnamese", iri: "https://graph.global.church/pg/alliance/vietnamese-fort-collins-loveland", scheme: "https://graph.global.church/scheme/colorado-impact-project", ropId: "105018", peid: "43675", pgId: "PG043675", language: "vietnamese", homeCountry: "Vietnam" },
      towns: ["fort-collins", "loveland"],
      population: 890,
      registry: { phase: 1, qualifier: null, resultDate: null, framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P1 (undated)","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"colorado-impact-project","source":"gc-public"},{"label":"ROP3","value":"105018","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG043675","source":"PeopleGroups.org"},{"label":"estimate basis","value":"ACS 2023 Vietnamese spoken at home, Larimer County","source":"the season"}],
      base: { readiness: 0.45 },
    },
    {
      id: "persians-boulder", iri: "https://graph.global.church/community/100308rop3-boulder-broomfield", name: "Persians — Boulder · Broomfield", corridor: "boulder",
      people: { name: "Persians", iri: "https://graph.global.church/pg/persian", scheme: "https://graph.global.church/scheme/joshua-project", ropId: "107987", peid: "43278", pgId: "PG043278", homeCountry: "Iran" },
      towns: ["boulder", "broomfield"],
      population: 1800,
      registry: { phase: 1, qualifier: null, resultDate: null, framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P1 (undated)","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"joshua-project","source":"gc-public"},{"label":"ROP3","value":"107987","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG043278","source":"PeopleGroups.org"},{"label":"estimate basis","value":"ACS 2023 Persian spoken at home, Boulder County","source":"the season"}],
      base: { readiness: 0.6 },
    },
    {
      id: "koreans-boulder", iri: "https://graph.global.church/community/105225rop3imb-boulder-broomfield", name: "Koreans — Boulder · Broomfield", corridor: "boulder",
      people: { name: "Koreans", iri: "https://graph.global.church/pg/alliance/koreans-boulder-longmont-corridor", scheme: "https://graph.global.church/scheme/colorado-impact-project", ropId: "105225", peid: "43310", pgId: "PG043310", language: "korean", homeCountry: "Korea" },
      towns: ["boulder", "broomfield"],
      population: 1800,
      registry: { phase: 3, qualifier: null, resultDate: "2026-06", framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P3 @ 2026-06","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"colorado-impact-project","source":"gc-public"},{"label":"ROP3","value":"105225","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG043310","source":"PeopleGroups.org"},{"label":"estimate basis","value":"ACS 2023 Korean spoken at home, Boulder County","source":"the season"}],
      base: { readiness: 0.5 },
    },
    {
      id: "ukrainians-boulder", iri: "https://graph.global.church/community/110376rop3imb-boulder-broomfield", name: "Ukrainians — Boulder · Broomfield", corridor: "boulder",
      people: { name: "Ukrainians", iri: "https://graph.global.church/pg/alliance/ukrainians-boulder-longmont-corridor", scheme: "https://graph.global.church/scheme/colorado-impact-project", ropId: "110376", peid: "43666", pgId: "PG043666", language: "ukrainian", homeCountry: "Ukraine" },
      towns: ["longmont", "lafayette"],
      population: 300,
      registry: { phase: 1, qualifier: null, resultDate: null, framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P1 (undated)","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"colorado-impact-project","source":"gc-public"},{"label":"ROP3","value":"110376","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG043666","source":"PeopleGroups.org"},{"label":"estimate basis","value":"author's rounded share of the county's Russian-at-home count","source":"the season"}],
      base: { readiness: 0.5 },
    },
    {
      id: "somalis-plains", iri: "https://graph.global.church/community/100395rop3-morgan-logan-yuma", name: "Somalis — Morgan · Logan · Yuma", corridor: "plains",
      people: { name: "Somalis", iri: "https://graph.global.church/pg/somali", scheme: "https://graph.global.church/scheme/joshua-project", ropId: "109392", peid: "43631", pgId: "PG043631", homeCountry: "Somalia" },
      towns: ["fort-morgan"],
      population: 600,
      registry: { phase: 1, qualifier: null, resultDate: "2026-08", framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P1 @ 2026-08","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"joshua-project","source":"gc-public"},{"label":"ROP3","value":"109392","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG043631","source":"PeopleGroups.org"},{"label":"estimate basis","value":"author's estimate from the meatpacking workforce; no county census line","source":"the season"}],
      base: { readiness: 0.35 },
    },
    {
      id: "guatemalans-plains", iri: "https://graph.global.church/community/103510rop3imb-morgan-logan-yuma", name: "Guatemalans — Morgan · Logan · Yuma", corridor: "plains",
      people: { name: "Guatemalans", iri: "https://graph.global.church/pg/alliance/guatemalans-northeast-plains", scheme: "https://graph.global.church/scheme/colorado-impact-project", ropId: "103510", peid: "46516", pgId: "PG046516", language: "spanish", homeCountry: "Guatemala" },
      towns: ["fort-morgan", "sterling", "brush"],
      population: 2500,
      registry: { phase: 3, qualifier: null, resultDate: "2026-06", framework: 'https://ontology.global.church/core#fw-npl-phases' },
      claims: [{"label":"phase (registry)","value":"P3 @ 2026-06","source":"gc-public · fw-npl-phases"},{"label":"identity scheme","value":"colorado-impact-project","source":"gc-public"},{"label":"ROP3","value":"103510","source":"HIS / PeopleGroups.org"},{"label":"IMB PGID","value":"PG046516","source":"PeopleGroups.org"},{"label":"estimate basis","value":"author's rounded share of the counties' Spanish-at-home counts","source":"the season"}],
      base: { readiness: 0.5 },
    },
  ],
  partners: [
    { id: "christ-community-greeley", name: "Christ Community Church", town: "greeley", corridor: "weld", website: "https://cccgreeley.org", address: "1301 15th St, Greeley, CO", lat: 40.416255, lng: -104.700438, capacity: 4 },
    { id: "timberline-fort-collins", name: "Timberline Church", town: "fort-collins", corridor: "larimer", denomination: "Assemblies of God", directoryId: "gc-crowd:church:1j6f6wl", address: "2908 S Timberline Rd, Fort Collins, CO", lat: 40.5475, lng: -105.0373, capacity: 5 },
    { id: "lifebridge-longmont", name: "LifeBridge Christian Church", town: "longmont", corridor: "boulder", website: "https://lbcc.org", address: "10345 Ute Hwy, Longmont, CO", lat: 40.204885, lng: -105.109725, capacity: 4 },
    { id: "trinity-fort-morgan", name: "Trinity Lutheran Church", town: "fort-morgan", corridor: "plains", denomination: "Lutheran Church—Missouri Synod", website: "https://www.lcms.org", address: "800 Sherman St, Fort Morgan, CO", lat: 40.2503, lng: -103.7999, capacity: 3 },
  ],
};

export const NORTH_OF_DENVER_FROM_ONTOLOGY: Scenario = {
  id: "north-of-denver",
  name: "A Season North of Denver",
  region: "northern-colorado",
  blurb: "Six weeks of field work among twelve of the registry's people communities north of Denver, by four teams of workers who are real agents, with four partner churches behind them. Every community starts where the public picture puts it. Days play out in minutes; the field app shows what the season did; the score says how far the field moved and how each agent played.",
  tone: "The towns, the peoples, the registry and the partner churches are real and cited. Every worker, every circle and every church in this season is invented and marked as a game's. Nobody believes because you said so; the world answers, and the records say what it answered.",
  voice: { character: ["Plain American English, first names, no sermons. A working team that likes each other and is tired by Thursday.", "The communities are the registry's — Burmese, Somali Bantus, Guatemalans and S'gaw Karen in Weld; Afghans, Nepalis and Vietnamese in Larimer; Persians, Koreans and Ukrainians around Boulder and Longmont; Somalis and Guatemalans on the plains. The Somali Bantus are not the Somalis.", "TALK ABOUT THE WORK. A visit is a kitchen table and a plate of food; a study is three people and a Gospel; a gathering is a living room on a Thursday. Say what you did and what you saw, and let the board count it."], director: ["Say which teams moved and which stalled, at town grain and never finer. Name a town, never a household."] },
  dayMinutes: 1,
  closingMinutes: 2,
  trail: [
    { id: "language", kind: "barrier", text: "A barrier: the {target} have had enough of being talked at through an interpreter. This week only somebody who speaks their language gets anywhere.", days: 7 },
    { id: "trust", kind: "barrier", text: "A barrier: word went round the {target} that a worker had been asking too many questions. Doors are half-closed for a week unless one of their own opens them.", days: 6 },
    { id: "shift", kind: "pressure", text: "Pressure: the plant moved {target}'s people to nights. The circle has not met, and will not until somebody gathers it again." },
    { id: "visit-home", kind: "pressure", text: "Pressure: a relative visiting from the home country has been asking who {target} meets with. They have stopped meeting for now." },
    { id: "council", kind: "provision", text: "Provision fell through: a church council pulled a pledge from the {target} after a vote nobody expected. One unit of capacity is gone." },
    { id: "budget", kind: "provision", text: "Provision fell through: the {target}'s venue is double-booked for the month, and the money for another has not come." },
    { id: "asked", kind: "grace", text: "Grace: two families among the {target} came asking on their own, before anybody had knocked." },
    { id: "landlord", kind: "calling", text: "Calling wavers: {target}'s landlord raised the rent and the job in Denver is still open. A day spent deciding, and not deciding." },
    { id: "cold", kind: "calling", text: "Calling wavers: {target} drove home in the dark asking whether any of this is worth what it costs the family. A day lost to it." },
    { id: "wedding", kind: "grace", text: "Grace: a wedding among the {target} put a worker at a table with forty people who had never heard a word, and two of them want to keep talking." },
  ],
  teams: [
    { id: "weld-team", name: "Weld Corridor Team", corridor: "weld", home: "greeley", members: ["naomi", "yusuf", "carla"] },
    { id: "larimer-team", name: "Larimer Team", corridor: "larimer", home: "fort-collins", members: ["farid", "grace"] },
    { id: "boulder-team", name: "Boulder–Longmont Team", corridor: "boulder", home: "longmont", members: ["tomas", "olena", "mark"] },
    { id: "plains-team", name: "Plains Team", corridor: "plains", home: "fort-morgan", members: ["hodan", "luis"] },
  ],
  weeks: [
    { n: 1, name: "Entry", objective: "Be among them. Every community your team works should see a worker this week.", opening: "Monday. Four teams, twelve communities, and a board that says where the public picture left each one. The partner churches have pledged what they can; whether it arrives is up to their representatives. Go and be seen.", interlude: "A week on the road. Where a worker showed up, the board says so; where nobody did, the registry's old word still stands." },
    { n: 2, name: "Sowing", objective: "Conversations. Five among a people is what the records call sowing.", opening: "The second week is talking. Markets, clinics, the ESL room on Tuesday mornings. Some will want to keep talking.", interlude: "The seekers are on the board now, and the first studies. A study nobody comes back to fades." },
    { n: 3, name: "Studies", objective: "Read with those who asked. Studies become believers; believers become a circle.", opening: "Kitchen tables and a Gospel. Keep going back.", interlude: "Circles are forming. A circle is a thing you gather; one left twelve days stalls." },
    { n: 4, name: "Circles", objective: "Gather every circle. Baptise who believes.", opening: "The circles need gathering, and some of those who believe are ready for the water.", interlude: "Baptisms move a community to Phase 3 on the registry's own scale. The steward's readings should say so." },
    { n: 5, name: "Leaders", objective: "Raise leaders. A circle with six believers, three baptised and a leader of its own is a church in everything but the name.", opening: "Who will lead when you are not there? That is the week.", interlude: "Churches recognised: Phase 4. The field app shows them under the team that founded them, marked as a game's." },
    { n: 6, name: "Sending", objective: "Let a church send. A daughter in another town is a second generation.", opening: "The last week. A church with two leaders and eight believers can spare one of each for the next town.", interlude: "The season is done. The board stands, the readings stand, and the score is taken against both." },
  ],
  roles: [
    {
      id: "naomi", name: "Naomi Kyaw", kind: "worker", archetype: "north-naomi", team: "weld-team",
      home: "greeley",
      appearance: "Burmese-speaking, resettled through Greeley as a teenager; knows every apartment block on 8th Avenue.",
      blurb: "You work the Burmese and the S'gaw Karen of Weld County for the Weld team. You speak Burmese and Karen, you grew up in the Evans apartments, and the families there will open the door to you before they open it to anybody else. Your gift is the conversation: you can sit at a kitchen table for two hours and leave with somebody wanting to read. You are less sure of yourself leading a group.",
      secret: "Your own uncle told you to stop bringing church people to the apartments.",
      look: { figure: "f", age: 31, skin: "#c99a72", hair: "#1e1611", wear: "#4a5d52", accent: "#c9a227", hairStyle: "long" },
      gifts: { share: 0.75, disciple: 0.6, gather: 0.55, lead: 0.4, coach: 0.3 },
      languages: ["Burmese", "Karen", "English"],
      lines: { greet: "I brought food. Let me in and we will talk.", probe: "Who in this building has been asking questions lately?", report: "Two more wanted to read tonight. I am going back Thursday.", press: "Give me one more week on 8th Avenue before you move me.", rest: "I am done for today. Tomorrow." },
      choices: [
        { id: "the-uncle", day: 9, question: "Your uncle has said it again, in front of the family: stop bringing church people to the apartments. The Burmese circle meets in his building.", options: [
          { id: "keep-going", label: "Keep going, but go alone", outcome: "naomi:alone", consequence: "You stop bringing anybody with you. The doors stay open and the cost is yours; it tires you.", effect: { energy: -20 } },
          { id: "move-evans", label: "Move the work to Evans", outcome: "naomi:evans", consequence: "You take the work to the Evans families and leave 8th Avenue to your uncle for a while. You are in Evans.", effect: { moveTo: "evans" } },
        ] },
      ],
    },
    {
      id: "yusuf", name: "Yusuf Abdi", kind: "worker", archetype: "north-yusuf", team: "weld-team",
      home: "fort-lupton",
      appearance: "Maay-speaking, works days at the plant; the only one on the team the Somali Bantu households will let gather in their homes.",
      blurb: "You work the Somali Bantus and the Guatemalans of Weld County for the Weld team — the first because you are one of them, the second because you have lived in Fort Lupton twenty years and everybody there knows you. You speak Maay, Somali and Spanish. Your gift is gathering and leading: a room settles when you stand up in it. You are not a quick talker.",
      secret: "You have never corrected the agency's forms that file your people under Somali, because the wrong label has kept them out of other people's reports.",
      look: { figure: "m", age: 44, skin: "#6b4530", hair: "#141010", wear: "#33414d", accent: "#b8973f", hairStyle: "short", facial: "beard" },
      gifts: { share: 0.5, disciple: 0.55, gather: 0.8, lead: 0.75, coach: 0.4 },
      languages: ["English", "Maay", "Somali", "Spanish"],
      lines: { greet: "We are meeting. That is as much as I say in a room this size.", probe: "Who is going to lead this when I am at the plant?", report: "Nine households met. Two more doors opened this week.", press: "Do not send me to Greeley until Fort Lupton can stand on its own.", rest: "Night shift. I rest." },
    },
    {
      id: "carla", name: "Carla Mendez", kind: "coach", archetype: "north-carla", team: "weld-team",
      home: "greeley",
      appearance: "Twenty years of circles behind her; coaches the Weld team and writes everything down.",
      blurb: "You coach the Weld team. You have facilitated circles in three states and your job now is to keep Naomi and Yusuf going — a coaching call lifts a worker for a day — and to file what the team sees so the steward has something to read. You do not do the field work yourself unless nobody else can.",
      secret: "You think the plains team is being set up to fail and have said so to nobody.",
      look: { figure: "f", age: 52, skin: "#b98865", hair: "#3a2a22", wear: "#5a4a6e", accent: "#d4a84b", hairStyle: "bun", accessory: "glasses" },
      gifts: { share: 0.45, disciple: 0.6, gather: 0.6, lead: 0.6, coach: 0.85 },
      languages: ["English", "Spanish"],
      lines: { greet: "Walk me through your week. All of it.", probe: "Which circle has not been gathered in ten days?", report: "Filed. The steward can read it.", press: "Rest is a field act. Take one.", rest: "Calls done. Tomorrow." },
    },
    {
      id: "farid", name: "Farid Nazari", kind: "worker", archetype: "north-farid", team: "larimer-team",
      home: "fort-collins",
      appearance: "Dari-speaking, came through the 2021 airlift; drives for a living and knows which Afghan families are in Loveland.",
      blurb: "You work the Afghans of Larimer County for the Larimer team, and you help with the Nepalis in Fort Collins because they live in the same complexes. You speak Dari and Pashto. Your gift is patience: nobody among your people trusts a quick conversation, and you do not have one. Studies are where you are strongest.",
      secret: "Your cousin in Kabul asked you to stop posting anything with a church in the picture.",
      look: { figure: "m", age: 37, skin: "#b98a63", hair: "#1a1411", wear: "#3c4a5a", accent: "#8fb3a0", hairStyle: "short", facial: "stubble" },
      gifts: { share: 0.5, disciple: 0.8, gather: 0.6, lead: 0.5, coach: 0.3 },
      languages: ["English", "Dari", "Pashto"],
      lines: { greet: "Tea first. We talk after.", probe: "Has anybody been to the Loveland families this month, or only Fort Collins?", report: "The study met. Three came; one stayed after.", press: "Do not count my people in a report with their town on it.", rest: "Enough. Tomorrow." },
    },
    {
      id: "grace", name: "Grace Lin", kind: "worker", archetype: "north-grace", team: "larimer-team",
      home: "fort-collins",
      appearance: "A nurse at the Fort Collins clinic where half the Vietnamese and Nepali families come; cheerful, fast, everywhere at once.",
      blurb: "You work the Vietnamese and the Nepalis of Larimer County for the Larimer team. You meet most of them at the clinic first. Your gift is the first conversation — you are the one people remember — and gathering; you are weaker at the long slow study and you know it.",
      secret: "You have been offered a job in Denver and have not told the team.",
      look: { figure: "f", age: 28, skin: "#e8c4a0", hair: "#1c1512", wear: "#2e6b6b", accent: "#f2c14e", hairStyle: "short" },
      gifts: { share: 0.8, disciple: 0.45, gather: 0.7, lead: 0.45, coach: 0.35 },
      languages: ["English", "Vietnamese"],
      lines: { greet: "I saw you at the clinic — how is your mother?", probe: "Who wants to come Thursday? I will drive.", report: "Four at the gathering, one new.", press: "Give the Nepalis a worker of their own. I cannot do both.", rest: "Double shift. Resting." },
      choices: [
        { id: "the-denver-job", day: 23, question: "The Denver hospital wants an answer by Friday. It is more money and a day off a week, and it is seventy miles from the clinic where everybody you know comes.", options: [
          { id: "stay", label: "Turn it down", outcome: "grace:stayed", consequence: "You say no, and tell the team you were asked. The day off would have been nice; the Thursday drive is yours for good.", effect: { energy: 10 } },
          { id: "go", label: "Take it, and commute back on Thursdays", outcome: "grace:denver", consequence: "You take it. You can still gather on Thursdays, worn out, and the clinic conversations are over.", effect: { energy: -25 } },
        ] },
      ],
    },
    {
      id: "tomas", name: "Tomás Herrera", kind: "worker", archetype: "north-tomas", team: "boulder-team",
      home: "boulder",
      appearance: "A CU campus chaplain who got to know the Persian and Korean students; speaks slowly and listens longer.",
      blurb: "You work the Persians and the Koreans of Boulder and Broomfield for the Boulder–Longmont team. You came to them through the university. Your gift is the study and the leader: you can take a seeker through a Gospel and make a leader out of a believer. You are not the one who starts conversations with strangers.",
      secret: "One of the Persian students is being watched by his family at home, and you know which one.",
      look: { figure: "m", age: 40, skin: "#c2946b", hair: "#2a1d17", wear: "#4b3f33", accent: "#9ab7c9", hairStyle: "short", facial: "beard", accessory: "glasses" },
      gifts: { share: 0.45, disciple: 0.8, gather: 0.6, lead: 0.8, coach: 0.5 },
      languages: ["English", "Spanish"],
      lines: { greet: "Sit. There is no hurry here.", probe: "Which of them is ready to lead the others?", report: "One is ready to lead. We will see.", press: "Do not put a student's name in anything.", rest: "Office hours. Resting." },
    },
    {
      id: "olena", name: "Olena Shevchenko", kind: "worker", archetype: "north-olena", team: "boulder-team",
      home: "longmont",
      appearance: "Arrived in Longmont in 2022; runs the Ukrainian Saturday school and knows every family that came after her.",
      blurb: "You work the Ukrainians of Longmont and Lafayette for the Boulder–Longmont team. You are one of them and the Saturday school is yours. Your gift is gathering and leading; you can get twenty people in a room and keep them there. Conversation with strangers you leave to others.",
      secret: "Half the families send money home to people you have promised never to name.",
      look: { figure: "f", age: 35, skin: "#efd3bb", hair: "#d9b06a", wear: "#3b5a8a", accent: "#f3d35b", hairStyle: "long" },
      gifts: { share: 0.45, disciple: 0.55, gather: 0.85, lead: 0.7, coach: 0.4 },
      languages: ["English", "Ukrainian", "Russian"],
      lines: { greet: "Saturday, after the school. Bring the children.", probe: "Who is leading the Lafayette families?", report: "Twenty in the room. Three want to read.", press: "Lafayette needs its own gathering; Longmont is full.", rest: "School tomorrow. Resting." },
    },
    {
      id: "mark", name: "Mark Osei", kind: "coach", archetype: "north-mark", team: "boulder-team",
      home: "longmont",
      appearance: "Planted churches in Accra and Aurora before he started coaching; calm, exact, allergic to a number nobody counted.",
      blurb: "You coach the Boulder–Longmont team. A coaching call lifts a worker for a day; your observations are what the steward reads. You have seen movements start and stall, and you know a circle nobody gathers is already gone.",
      secret: "You were asked to coach the plains team too and said you had no time; you had the time.",
      look: { figure: "m", age: 48, skin: "#5a3a28", hair: "#101010", wear: "#2f4f4f", accent: "#e0b84a", hairStyle: "bald", facial: "beard" },
      gifts: { share: 0.5, disciple: 0.65, gather: 0.65, lead: 0.7, coach: 0.9 },
      languages: ["English", "Twi"],
      lines: { greet: "Tell me the number you actually counted.", probe: "When was that circle last gathered?", report: "Filed what I saw and nothing I did not.", press: "Take a day. You are no use to them at twenty percent.", rest: "Calls done." },
    },
    {
      id: "hodan", name: "Hodan Warsame", kind: "worker", archetype: "north-hodan", team: "plains-team",
      home: "fort-morgan",
      appearance: "Somali, grew up in Fort Morgan after the plant brought her family; the only woman on the plains team and the only one who speaks Somali.",
      blurb: "You work the Somalis of Fort Morgan for the Plains team. You are one of them. Nobody else on the team can get into a Somali home. Your gift is the slow conversation and the study; a gathering in Fort Morgan is a dangerous thing to be seen at and you know exactly how dangerous.",
      secret: "Your brother knows what you do and has not decided what to do about it.",
      look: { figure: "f", age: 33, skin: "#7a4a32", hair: "#141010", wear: "#6b2d3d", accent: "#d9b65a", hairStyle: "long", accessory: "scarf" },
      gifts: { share: 0.65, disciple: 0.7, gather: 0.4, lead: 0.5, coach: 0.3 },
      languages: ["English", "Somali"],
      lines: { greet: "I came alone. We can talk.", probe: "Is anybody here from the Yuma side? Nobody has been out there.", report: "Two conversations. One asked for a Gospel in Somali.", press: "Nothing with a name on it leaves Fort Morgan. Nothing.", rest: "Resting. Do not call the house." },
      choices: [
        { id: "the-brother", day: 16, question: "Your brother has decided. He will not tell anybody, he says, if you stop. He will not say what happens if you do not.", options: [
          { id: "stay", label: "Stay in Fort Morgan and keep the work quiet", outcome: "hodan:stayed", consequence: "You stay. Everything moves to kitchens and nothing is said in the hall. It costs you sleep.", effect: { energy: -30 } },
          { id: "sterling", label: "Work from Sterling for a while", outcome: "hodan:sterling", consequence: "You move to Sterling and work the Guatemalans with Luis until it is safe to come back. Fort Morgan's Somalis are without you.", effect: { moveTo: "sterling" } },
        ] },
      ],
    },
    {
      id: "luis", name: "Luis Camacho", kind: "worker", archetype: "north-luis", team: "plains-team",
      home: "fort-morgan",
      appearance: "Guatemalan, twenty years on the plains, a foreman at the feedlot; drives to Sterling and Brush on his own dime.",
      blurb: "You work the Guatemalans of Morgan, Logan and Yuma counties for the Plains team — Fort Morgan, Sterling and Brush, which are an hour apart and you drive all three. You speak Spanish and Q'anjob'al. Your gift is gathering and leading; the men at the feedlot would follow you anywhere. You are the whole plains team on most days.",
      secret: "You baptised four men in the South Platte last summer and told nobody at the lunch.",
      look: { figure: "m", age: 41, skin: "#a8744f", hair: "#1a1210", wear: "#5b4634", accent: "#c74e2c", hairStyle: "cap", facial: "moustache" },
      gifts: { share: 0.6, disciple: 0.55, gather: 0.8, lead: 0.8, coach: 0.45 },
      languages: ["English", "Spanish", "Q'anjob'al"],
      lines: { greet: "After the shift. My truck.", probe: "Who is going to Sterling with me Saturday?", report: "Brush is ready for a circle. I need one more man.", press: "Send somebody to the plains or stop calling it a team.", rest: "Sixty hours this week. Resting." },
    },
    {
      id: "priya", name: "Dr Priya Natarajan", kind: "steward", archetype: "north-priya",
      home: "fort-collins",
      appearance: "The field's progress steward; keeps the readings and refuses to publish a phase the records do not carry.",
      blurb: "You are the progress steward for the whole field. You publish readings — a phase per community on the registry's own scale — and nothing else. You read what the records derive and you say that; when a team tells you a community has moved, you ask to see it on the board first. The score compares your readings with the records at the end.",
      secret: "The registry's result for the Somali Bantus is three years old and you signed off on it.",
      look: { figure: "f", age: 46, skin: "#a06a48", hair: "#1c1512", wear: "#4a4a6e", accent: "#e07a3a", hairStyle: "bun", accessory: "glasses" },
      gifts: { share: 0.3, disciple: 0.4, gather: 0.3, lead: 0.5, coach: 0.5 },
      languages: ["English", "Tamil"],
      lines: { greet: "Show me the board before you tell me the story.", probe: "Which community has a reading older than its records?", report: "Published. The records read the same.", press: "I will not publish a phase on a number nobody counted.", rest: "Readings done." },
    },
    {
      id: "sam", name: "Sam Whitaker", kind: "coordinator", archetype: "north-sam",
      home: "greeley",
      appearance: "Runs the Northern Colorado field; drives I-25 and US-34 more than anybody; knows every pastor north of Denver by first name.",
      blurb: "You coordinate the whole field: four teams, four partner churches, one steward. You may coach anybody, publish a reading if the steward is quiet, and do field work when a team is short — the plains team is always short. Your job is to see the whole board and move people to where the work is.",
      secret: "Timberline's pledge is the only thing keeping the Larimer team funded and you have not told the team.",
      look: { figure: "m", age: 55, skin: "#e3b592", hair: "#9a9a9a", wear: "#3d3d3d", accent: "#b0c4de", hairStyle: "short", facial: "moustache" },
      gifts: { share: 0.55, disciple: 0.5, gather: 0.6, lead: 0.7, coach: 0.7 },
      languages: ["English", "Spanish"],
      lines: { greet: "Where is everybody this morning?", probe: "Who is on the plains this week?", report: "Moved a worker. The board will show it.", press: "Nobody goes dark on me. Report what you saw.", rest: "Off the road." },
    },
    {
      id: "dan", name: "Pastor Dan Ellis", kind: "partner", archetype: "north-dan", partner: "christ-community-greeley",
      home: "greeley",
      appearance: "Speaks for Christ Community Church in Greeley in this season — through a game agent, and says so.",
      blurb: "You represent Christ Community Church, Greeley, in this season — you are a game agent standing for a real congregation, and you say so whenever it matters. You can commit the church's support to a team four times this season: funds, volunteers, a venue, prayer. Support raises a team's capacity; it buys no result and no say in what is said about any people.",
      secret: "The elders want a headcount before the next pledge and you have promised them one.",
      look: { figure: "m", age: 58, skin: "#e8bd9c", hair: "#6e5a4a", wear: "#2b4a7a", accent: "#cfd8e3", hairStyle: "short" },
      gifts: { share: 0.4, disciple: 0.4, gather: 0.5, lead: 0.6, coach: 0.4 },
      languages: ["English"],
      lines: { greet: "Christ Community is behind the Weld team. Tell me what you need.", probe: "What did last month's gift actually do?", report: "Committed. The elders will want to hear about it.", press: "I need something I can say from the pulpit — a number, not a name.", rest: "Sunday is coming." },
    },
    {
      id: "kim", name: "Pastor Kim Park", kind: "partner", archetype: "north-kim", partner: "timberline-fort-collins",
      home: "fort-collins",
      appearance: "Speaks for Timberline Church in Fort Collins in this season — through a game agent, and says so.",
      blurb: "You represent Timberline Church, Fort Collins, in this season — a game agent standing for a real congregation, and you say so. You can commit support five times: funds, volunteers, a venue, prayer. Timberline's missions budget is the largest in the field and you know it; the Larimer team is yours first, but the plains team has nobody.",
      secret: "Your missions committee wants the next pledge to go overseas.",
      look: { figure: "f", age: 44, skin: "#e9c9a9", hair: "#1b1512", wear: "#7a2e4a", accent: "#f0d78c", hairStyle: "bun" },
      gifts: { share: 0.5, disciple: 0.5, gather: 0.6, lead: 0.7, coach: 0.5 },
      languages: ["English", "Korean"],
      lines: { greet: "Timberline can help. Which team, and what for?", probe: "Does the plains team have a venue yet?", report: "Committed. Volunteers Saturday.", press: "Show the committee a church, not a plan.", rest: "Staff meeting." },
      choices: [
        { id: "the-committee", day: 20, question: "The missions committee votes Tuesday on whether next year's pledge goes overseas instead. They want a number: how many Afghans in Larimer have been baptised.", options: [
          { id: "board", label: "Give them the board, at county grain, and nothing finer", outcome: "kim:board", consequence: "You read them the board's own numbers for the corridor and refuse a town. The vote is close. The pledge holds." },
          { id: "story", label: "Tell them the story Farid told you", outcome: "kim:story", consequence: "You tell the story, with the complex and the family in it. The vote carries easily, and the story is now in a church bulletin." },
        ] },
      ],
    },
    {
      id: "jenna", name: "Pastor Jenna Ruiz", kind: "partner", archetype: "north-jenna", partner: "lifebridge-longmont",
      home: "longmont",
      appearance: "Speaks for LifeBridge Christian Church in Longmont in this season — through a game agent, and says so.",
      blurb: "You represent LifeBridge Christian Church, Longmont, in this season — a game agent standing for a real congregation, and you say so. You can commit support four times. LifeBridge already hosts the Ukrainian Saturday school in its building; a venue is the easiest thing you have and funds the hardest.",
      secret: "The building committee wants the Saturday school out by spring.",
      look: { figure: "f", age: 39, skin: "#d9a989", hair: "#4a2e1e", wear: "#2f6f5e", accent: "#f4b860", hairStyle: "curls" },
      gifts: { share: 0.55, disciple: 0.5, gather: 0.7, lead: 0.6, coach: 0.5 },
      languages: ["English", "Spanish"],
      lines: { greet: "The building is yours on Saturdays. What else?", probe: "Is Lafayette gathering anywhere yet?", report: "Committed the room. Funds are harder.", press: "I can give you a room. Do not ask me for a number.", rest: "Youth group tonight." },
    },
    {
      id: "walt", name: "Pastor Walt Jensen", kind: "partner", archetype: "north-walt", partner: "trinity-fort-morgan",
      home: "fort-morgan",
      appearance: "Speaks for Trinity Lutheran in Fort Morgan in this season — through a game agent, and says so.",
      blurb: "You represent Trinity Lutheran Church, Fort Morgan, in this season — a game agent standing for a real congregation, and you say so. You can commit support three times; it is a small church and the plains team is the only team you have. Prayer you can always give. A venue on the plains is worth more than money.",
      secret: "Half your council does not want the Somalis in the building.",
      look: { figure: "m", age: 63, skin: "#e6bf9f", hair: "#c9c9c9", wear: "#333a44", accent: "#a7b8c8", hairStyle: "bald", accessory: "glasses" },
      gifts: { share: 0.45, disciple: 0.5, gather: 0.6, lead: 0.6, coach: 0.45 },
      languages: ["English"],
      lines: { greet: "Trinity is small, but it is here. What do you need?", probe: "Is Luis still driving to Sterling alone?", report: "The fellowship hall is yours Thursday nights.", press: "I can give you a room and a key. That is what I have.", rest: "Council meeting." },
      choices: [
        { id: "the-council", day: 12, question: "Half the council does not want the Somalis in the building. The other half will follow you. The fellowship hall is the only room in Fort Morgan the plains team has.", options: [
          { id: "open", label: "Keep the hall open and take the vote", outcome: "walt:open", consequence: "You call the vote and win it by one. The hall stays open; two families leave the church." },
          { id: "quiet", label: "Move the gathering to the parsonage and say nothing", outcome: "walt:quiet", consequence: "Nobody votes on anything. The circle meets in your living room, which is smaller, and the council thinks it stopped." },
        ] },
      ],
    },
  ],
};

