/**
 * COUNTRY CEILINGS — the most a mission's place may be shown, per country, whatever the mission asked for.
 *
 * Ported 2026-09-14 from Gather27's table (`~/engage`, generated from Joshua Project's country-level
 * SecurityLevel: 2 → `none`, 1 → `adm2`, 0 → `precise`), with the same caveat that table carries: the
 * source is unsourced and unversioned, so this is a STARTING POINT the card room's operators own, never
 * an authority that silently decides which countries are dangerous. A mission's own precision toggle is a
 * request; this is the ceiling, applied at write time AND at read time (`displayPoint`), so a change here
 * coarsens or hides every existing registration without anybody re-registering.
 *
 * `none` — no point and no country centroid: the mission is listed by name and country only.
 * `adm2` — the country's centroid (the card room keeps no district boundaries; Gather27 resolves a
 *          district here, and that is the natural next step).
 * `precise` — the geocoded point, or a ~3 km grid snap when the mission turned precision off.
 */
export type CountryCeiling = 'precise' | 'adm2' | 'none';

export interface CountryCeilingRow {
  /** ISO 3166-1 alpha-2. */
  readonly iso: string;
  /** For matching a free-text country value too (HubSpot intake, legacy rows without an ISO code). */
  readonly name: string;
  readonly ceiling: CountryCeiling;
  /** Joshua Project SecurityLevel, 0-2, as seeded — see the module doc's caveat. */
  readonly jpLevel: 0 | 1 | 2;
}

export const COUNTRY_CEILINGS: readonly CountryCeilingRow[] = [
  { iso: 'AF', name: 'Afghanistan', ceiling: 'none', jpLevel: 2 },
  { iso: 'DZ', name: 'Algeria', ceiling: 'none', jpLevel: 2 },
  { iso: 'AZ', name: 'Azerbaijan', ceiling: 'none', jpLevel: 2 },
  { iso: 'BH', name: 'Bahrain', ceiling: 'none', jpLevel: 2 },
  { iso: 'BD', name: 'Bangladesh', ceiling: 'none', jpLevel: 2 },
  { iso: 'BT', name: 'Bhutan', ceiling: 'none', jpLevel: 2 },
  { iso: 'BN', name: 'Brunei', ceiling: 'none', jpLevel: 2 },
  { iso: 'BF', name: 'Burkina Faso', ceiling: 'none', jpLevel: 2 },
  { iso: 'CF', name: 'Central African Republic', ceiling: 'none', jpLevel: 2 },
  { iso: 'TD', name: 'Chad', ceiling: 'none', jpLevel: 2 },
  { iso: 'CN', name: 'China', ceiling: 'none', jpLevel: 2 },
  { iso: 'CO', name: 'Colombia', ceiling: 'none', jpLevel: 2 },
  { iso: 'KM', name: 'Comoros', ceiling: 'none', jpLevel: 2 },
  { iso: 'CD', name: 'Congo, Democratic Republic of', ceiling: 'none', jpLevel: 2 },
  { iso: 'CU', name: 'Cuba', ceiling: 'none', jpLevel: 2 },
  { iso: 'DJ', name: 'Djibouti', ceiling: 'none', jpLevel: 2 },
  { iso: 'EG', name: 'Egypt', ceiling: 'none', jpLevel: 2 },
  { iso: 'ER', name: 'Eritrea', ceiling: 'none', jpLevel: 2 },
  { iso: 'IN', name: 'India', ceiling: 'none', jpLevel: 2 },
  { iso: 'ID', name: 'Indonesia', ceiling: 'none', jpLevel: 2 },
  { iso: 'IR', name: 'Iran', ceiling: 'none', jpLevel: 2 },
  { iso: 'IQ', name: 'Iraq', ceiling: 'none', jpLevel: 2 },
  { iso: 'KZ', name: 'Kazakhstan', ceiling: 'none', jpLevel: 2 },
  { iso: 'KP', name: 'Korea, North', ceiling: 'none', jpLevel: 2 },
  { iso: 'KW', name: 'Kuwait', ceiling: 'none', jpLevel: 2 },
  { iso: 'KG', name: 'Kyrgyzstan', ceiling: 'none', jpLevel: 2 },
  { iso: 'LA', name: 'Laos', ceiling: 'none', jpLevel: 2 },
  { iso: 'LY', name: 'Libya', ceiling: 'none', jpLevel: 2 },
  { iso: 'MY', name: 'Malaysia', ceiling: 'none', jpLevel: 2 },
  { iso: 'MV', name: 'Maldives', ceiling: 'none', jpLevel: 2 },
  { iso: 'ML', name: 'Mali', ceiling: 'none', jpLevel: 2 },
  { iso: 'MR', name: 'Mauritania', ceiling: 'none', jpLevel: 2 },
  { iso: 'MA', name: 'Morocco', ceiling: 'none', jpLevel: 2 },
  { iso: 'MZ', name: 'Mozambique', ceiling: 'none', jpLevel: 2 },
  { iso: 'MM', name: 'Myanmar (Burma)', ceiling: 'none', jpLevel: 2 },
  { iso: 'NE', name: 'Niger', ceiling: 'none', jpLevel: 2 },
  { iso: 'NG', name: 'Nigeria', ceiling: 'none', jpLevel: 2 },
  { iso: 'OM', name: 'Oman', ceiling: 'none', jpLevel: 2 },
  { iso: 'PK', name: 'Pakistan', ceiling: 'none', jpLevel: 2 },
  { iso: 'QA', name: 'Qatar', ceiling: 'none', jpLevel: 2 },
  { iso: 'SA', name: 'Saudi Arabia', ceiling: 'none', jpLevel: 2 },
  { iso: 'SO', name: 'Somalia', ceiling: 'none', jpLevel: 2 },
  { iso: 'SD', name: 'Sudan', ceiling: 'none', jpLevel: 2 },
  { iso: 'SY', name: 'Syria', ceiling: 'none', jpLevel: 2 },
  { iso: 'TJ', name: 'Tajikistan', ceiling: 'none', jpLevel: 2 },
  { iso: 'TN', name: 'Tunisia', ceiling: 'none', jpLevel: 2 },
  { iso: 'TM', name: 'Turkmenistan', ceiling: 'none', jpLevel: 2 },
  { iso: 'TR', name: 'Türkiye (Turkey)', ceiling: 'none', jpLevel: 2 },
  { iso: 'AE', name: 'United Arab Emirates', ceiling: 'none', jpLevel: 2 },
  { iso: 'UZ', name: 'Uzbekistan', ceiling: 'none', jpLevel: 2 },
  { iso: 'VN', name: 'Vietnam', ceiling: 'none', jpLevel: 2 },
  { iso: 'EH', name: 'Western Sahara', ceiling: 'none', jpLevel: 2 },
  { iso: 'YE', name: 'Yemen', ceiling: 'none', jpLevel: 2 },
  { iso: 'KH', name: 'Cambodia', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'CM', name: 'Cameroon', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'HK', name: 'China, Hong Kong', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'MO', name: 'China, Macau', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'CI', name: 'Côte d\'Ivoire', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'ET', name: 'Ethiopia', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'GM', name: 'Gambia', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'GH', name: 'Ghana', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'GN', name: 'Guinea', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'JO', name: 'Jordan', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'XK', name: 'Kosovo', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'LB', name: 'Lebanon', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'YT', name: 'Mayotte', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'MX', name: 'Mexico', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'MN', name: 'Mongolia', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'NP', name: 'Nepal', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'NI', name: 'Nicaragua', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'RU', name: 'Russia', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'SN', name: 'Senegal', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'RS', name: 'Serbia', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'SS', name: 'South Sudan', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'LK', name: 'Sri Lanka', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'TZ', name: 'Tanzania', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'PS', name: 'West Bank / Gaza', ceiling: 'adm2', jpLevel: 1 },
  { iso: 'AL', name: 'Albania', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AS', name: 'American Samoa', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AD', name: 'Andorra', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AO', name: 'Angola', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AI', name: 'Anguilla', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AG', name: 'Antigua and Barbuda', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AR', name: 'Argentina', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AM', name: 'Armenia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AW', name: 'Aruba', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AU', name: 'Australia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'AT', name: 'Austria', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BS', name: 'Bahamas', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BB', name: 'Barbados', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BY', name: 'Belarus', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BE', name: 'Belgium', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BZ', name: 'Belize', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BJ', name: 'Benin', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BM', name: 'Bermuda', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BO', name: 'Bolivia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BA', name: 'Bosnia-Herzegovina', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BW', name: 'Botswana', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BR', name: 'Brazil', ceiling: 'precise', jpLevel: 0 },
  { iso: 'IO', name: 'British Indian Ocean Territory', ceiling: 'precise', jpLevel: 0 },
  { iso: 'VG', name: 'British Virgin Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BG', name: 'Bulgaria', ceiling: 'precise', jpLevel: 0 },
  { iso: 'BI', name: 'Burundi', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CA', name: 'Canada', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CV', name: 'Cape Verde', ceiling: 'precise', jpLevel: 0 },
  { iso: 'KY', name: 'Cayman Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CL', name: 'Chile', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CX', name: 'Christmas Island', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CC', name: 'Cocos (Keeling) Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CG', name: 'Congo, Republic of the', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CK', name: 'Cook Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CR', name: 'Costa Rica', ceiling: 'precise', jpLevel: 0 },
  { iso: 'HR', name: 'Croatia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CW', name: 'Curacao', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CY', name: 'Cyprus', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CZ', name: 'Czechia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'DK', name: 'Denmark', ceiling: 'precise', jpLevel: 0 },
  { iso: 'DM', name: 'Dominica', ceiling: 'precise', jpLevel: 0 },
  { iso: 'DO', name: 'Dominican Republic', ceiling: 'precise', jpLevel: 0 },
  { iso: 'EC', name: 'Ecuador', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SV', name: 'El Salvador', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GQ', name: 'Equatorial Guinea', ceiling: 'precise', jpLevel: 0 },
  { iso: 'EE', name: 'Estonia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SZ', name: 'Eswatini', ceiling: 'precise', jpLevel: 0 },
  { iso: 'FK', name: 'Falkland Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'FO', name: 'Faroe Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'FJ', name: 'Fiji', ceiling: 'precise', jpLevel: 0 },
  { iso: 'FI', name: 'Finland', ceiling: 'precise', jpLevel: 0 },
  { iso: 'FR', name: 'France', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GF', name: 'French Guiana', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PF', name: 'French Polynesia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GA', name: 'Gabon', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GE', name: 'Georgia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'DE', name: 'Germany', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GI', name: 'Gibraltar', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GR', name: 'Greece', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GL', name: 'Greenland', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GD', name: 'Grenada', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GP', name: 'Guadeloupe', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GU', name: 'Guam', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GT', name: 'Guatemala', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GW', name: 'Guinea-Bissau', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GY', name: 'Guyana', ceiling: 'precise', jpLevel: 0 },
  { iso: 'HT', name: 'Haiti', ceiling: 'precise', jpLevel: 0 },
  { iso: 'HN', name: 'Honduras', ceiling: 'precise', jpLevel: 0 },
  { iso: 'HU', name: 'Hungary', ceiling: 'precise', jpLevel: 0 },
  { iso: 'IS', name: 'Iceland', ceiling: 'precise', jpLevel: 0 },
  { iso: 'IE', name: 'Ireland', ceiling: 'precise', jpLevel: 0 },
  { iso: 'IM', name: 'Isle of Man', ceiling: 'precise', jpLevel: 0 },
  { iso: 'IL', name: 'Israel', ceiling: 'precise', jpLevel: 0 },
  { iso: 'IT', name: 'Italy', ceiling: 'precise', jpLevel: 0 },
  { iso: 'JM', name: 'Jamaica', ceiling: 'precise', jpLevel: 0 },
  { iso: 'JP', name: 'Japan', ceiling: 'precise', jpLevel: 0 },
  { iso: 'KE', name: 'Kenya', ceiling: 'precise', jpLevel: 0 },
  { iso: 'KI', name: 'Kiribati (Gilbert)', ceiling: 'precise', jpLevel: 0 },
  { iso: 'KR', name: 'Korea, South', ceiling: 'precise', jpLevel: 0 },
  { iso: 'LV', name: 'Latvia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'LS', name: 'Lesotho', ceiling: 'precise', jpLevel: 0 },
  { iso: 'LR', name: 'Liberia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'LI', name: 'Liechtenstein', ceiling: 'precise', jpLevel: 0 },
  { iso: 'LT', name: 'Lithuania', ceiling: 'precise', jpLevel: 0 },
  { iso: 'LU', name: 'Luxembourg', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MG', name: 'Madagascar', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MW', name: 'Malawi', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MT', name: 'Malta', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MH', name: 'Marshall Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MQ', name: 'Martinique', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MU', name: 'Mauritius', ceiling: 'precise', jpLevel: 0 },
  { iso: 'FM', name: 'Micronesia, Federated States', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MD', name: 'Moldova', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MC', name: 'Monaco', ceiling: 'precise', jpLevel: 0 },
  { iso: 'ME', name: 'Montenegro', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MS', name: 'Montserrat', ceiling: 'precise', jpLevel: 0 },
  { iso: 'NA', name: 'Namibia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'NR', name: 'Nauru', ceiling: 'precise', jpLevel: 0 },
  { iso: 'NL', name: 'Netherlands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'NC', name: 'New Caledonia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'NZ', name: 'New Zealand', ceiling: 'precise', jpLevel: 0 },
  { iso: 'NU', name: 'Niue', ceiling: 'precise', jpLevel: 0 },
  { iso: 'NF', name: 'Norfolk Island', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MK', name: 'North Macedonia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'MP', name: 'Northern Mariana Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'NO', name: 'Norway', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PW', name: 'Palau', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PA', name: 'Panama', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PG', name: 'Papua New Guinea', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PY', name: 'Paraguay', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PE', name: 'Peru', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PH', name: 'Philippines', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PN', name: 'Pitcairn Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PL', name: 'Poland', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PT', name: 'Portugal', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PR', name: 'Puerto Rico', ceiling: 'precise', jpLevel: 0 },
  { iso: 'RE', name: 'Reunion', ceiling: 'precise', jpLevel: 0 },
  { iso: 'RO', name: 'Romania', ceiling: 'precise', jpLevel: 0 },
  { iso: 'RW', name: 'Rwanda', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SH', name: 'Saint Helena', ceiling: 'precise', jpLevel: 0 },
  { iso: 'KN', name: 'Saint Kitts and Nevis', ceiling: 'precise', jpLevel: 0 },
  { iso: 'LC', name: 'Saint Lucia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'PM', name: 'Saint Pierre and Miquelon', ceiling: 'precise', jpLevel: 0 },
  { iso: 'WS', name: 'Samoa', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SM', name: 'San Marino', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SC', name: 'Seychelles', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SL', name: 'Sierra Leone', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SG', name: 'Singapore', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SX', name: 'Sint Maarten', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SK', name: 'Slovakia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SI', name: 'Slovenia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SB', name: 'Solomon Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'ZA', name: 'South Africa', ceiling: 'precise', jpLevel: 0 },
  { iso: 'ES', name: 'Spain', ceiling: 'precise', jpLevel: 0 },
  { iso: 'VC', name: 'St Vincent and Grenadines', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SR', name: 'Suriname', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SJ', name: 'Svalbard', ceiling: 'precise', jpLevel: 0 },
  { iso: 'SE', name: 'Sweden', ceiling: 'precise', jpLevel: 0 },
  { iso: 'CH', name: 'Switzerland', ceiling: 'precise', jpLevel: 0 },
  { iso: 'ST', name: 'São Tomé and Príncipe', ceiling: 'precise', jpLevel: 0 },
  { iso: 'TW', name: 'Taiwan', ceiling: 'precise', jpLevel: 0 },
  { iso: 'TH', name: 'Thailand', ceiling: 'precise', jpLevel: 0 },
  { iso: 'TL', name: 'Timor-Leste', ceiling: 'precise', jpLevel: 0 },
  { iso: 'TG', name: 'Togo', ceiling: 'precise', jpLevel: 0 },
  { iso: 'TK', name: 'Tokelau', ceiling: 'precise', jpLevel: 0 },
  { iso: 'TO', name: 'Tonga', ceiling: 'precise', jpLevel: 0 },
  { iso: 'TT', name: 'Trinidad and Tobago', ceiling: 'precise', jpLevel: 0 },
  { iso: 'TC', name: 'Turks and Caicos Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'TV', name: 'Tuvalu', ceiling: 'precise', jpLevel: 0 },
  { iso: 'UG', name: 'Uganda', ceiling: 'precise', jpLevel: 0 },
  { iso: 'UA', name: 'Ukraine', ceiling: 'precise', jpLevel: 0 },
  { iso: 'GB', name: 'United Kingdom', ceiling: 'precise', jpLevel: 0 },
  { iso: 'US', name: 'United States', ceiling: 'precise', jpLevel: 0 },
  { iso: 'UY', name: 'Uruguay', ceiling: 'precise', jpLevel: 0 },
  { iso: 'VU', name: 'Vanuatu', ceiling: 'precise', jpLevel: 0 },
  { iso: 'VA', name: 'Vatican City', ceiling: 'precise', jpLevel: 0 },
  { iso: 'VE', name: 'Venezuela', ceiling: 'precise', jpLevel: 0 },
  { iso: 'VI', name: 'Virgin Islands (U.S.)', ceiling: 'precise', jpLevel: 0 },
  { iso: 'WF', name: 'Wallis and Futuna Islands', ceiling: 'precise', jpLevel: 0 },
  { iso: 'ZM', name: 'Zambia', ceiling: 'precise', jpLevel: 0 },
  { iso: 'ZW', name: 'Zimbabwe', ceiling: 'precise', jpLevel: 0 },
];
